# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Webefinity Switch Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - run: dotnet tool update -g docfx
    - name: Rebuild in Release
      run: dotnet build --no-restore --configuration Release
    - name: Publish NuGet Package
      run: dotnet nuget push src/Switch/bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
    - name: Publish
      run: docfx src/Switch.Doc/docfx.json
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'docs/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
